{
  "version": "3.8",
  "services": {
    "kong": {
      "image": "kong:latest",
      "environment": {
        "KONG_DATABASE": "off",
        "KONG_DECLARATIVE_CONFIG": "/kong/declarative/kong.yml",
        "KONG_PROXY_ACCESS_LOG": "/dev/stdout",
        "KONG_ADMIN_ACCESS_LOG": "/dev/stdout",
        "KONG_PROXY_ERROR_LOG": "/dev/stderr",
        "KONG_ADMIN_ERROR_LOG": "/dev/stderr",
        "KONG_ADMIN_LISTEN": "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      },
      "ports": [
        "8000:8000",
        "8443:8443",
        "8001:8001",
        "8444:8444"
      ],
      "volumes": [
        "./kong.yml:/kong/declarative/kong.yml"
      ],
      "healthcheck": {
        "test": [
          "CMD",
          "kong",
          "health"
        ],
        "interval": "10s",
        "timeout": "10s",
        "retries": 10
      }
    }
  }
}